// <auto-generated />
using System;
using DataAndModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAndModels.Migrations
{
    [DbContext(typeof(MonokayuDbContext))]
    [Migration("20210211184125_UpdatingTaskCommentsTable")]
    partial class UpdatingTaskCommentsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DataAndModels.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DataAndModels.Project2", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("projectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectID");

                    b.ToTable("Projects2");
                });

            modelBuilder.Entity("DataAndModels.Revision", b =>
                {
                    b.Property<int>("RevisionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime>("deadline")
                        .HasColumnType("datetime2");

                    b.HasKey("RevisionID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Revisions");
                });

            modelBuilder.Entity("DataAndModels.RevisionTask", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("RevisionID")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("links")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("progress")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("urgency")
                        .HasColumnType("int");

                    b.HasKey("TaskID");

                    b.HasIndex("RevisionID");

                    b.ToTable("RevisionTasks");
                });

            modelBuilder.Entity("DataAndModels.TaskComment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime2");

                    b.HasKey("CommentID");

                    b.HasIndex("TaskID");

                    b.ToTable("TaskComments");
                });

            modelBuilder.Entity("DataAndModels.User2", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("securityLevel")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("Users2");
                });

            modelBuilder.Entity("DataAndModels.UserProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("projectID")
                        .HasColumnType("int");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("projectID");

                    b.HasIndex("userID");

                    b.ToTable("UserProjects");
                });

            modelBuilder.Entity("DataAndModels.Revision", b =>
                {
                    b.HasOne("DataAndModels.Project2", "Project")
                        .WithMany("Revisions")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DataAndModels.RevisionTask", b =>
                {
                    b.HasOne("DataAndModels.Revision", "Revision")
                        .WithMany("RevisionTasks")
                        .HasForeignKey("RevisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("DataAndModels.TaskComment", b =>
                {
                    b.HasOne("DataAndModels.RevisionTask", "RevisionTask")
                        .WithMany("TaskComments")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RevisionTask");
                });

            modelBuilder.Entity("DataAndModels.UserProject", b =>
                {
                    b.HasOne("DataAndModels.Project2", "Projects2")
                        .WithMany("UserProjects")
                        .HasForeignKey("projectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAndModels.User2", "Users2")
                        .WithMany("UserProjects")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projects2");

                    b.Navigation("Users2");
                });

            modelBuilder.Entity("DataAndModels.Project2", b =>
                {
                    b.Navigation("Revisions");

                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("DataAndModels.Revision", b =>
                {
                    b.Navigation("RevisionTasks");
                });

            modelBuilder.Entity("DataAndModels.RevisionTask", b =>
                {
                    b.Navigation("TaskComments");
                });

            modelBuilder.Entity("DataAndModels.User2", b =>
                {
                    b.Navigation("UserProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
